/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String hart_icon = "assets/images/hart_icon.svg";
  static const String Home_icon = "assets/images/Home-icon.svg";
  static const String menu_icon = "assets/images/menu_icon.svg";
  static const String profile_image = "assets/images/profile_image.png";
  static const String settings_icon = "assets/images/settings_icon.svg";
}
